### ISSUE TITLE
Multivalue output, regex and metric

### ISSUE THREAD

**Issue by dlezcano** [ARM-software/workload-automation#1006]
Hi,
I'm running a mpv workload on Linux, the output gives:

AV: 00:00:00 / 00:02:23 (0%) A-V:  0.034
AV: 00:00:00 / 00:02:23 (0%) A-V:  0.061
AV: 00:00:00 / 00:02:23 (0%) A-V:  0.077
AV: 00:00:00 / 00:02:23 (0%) A-V:  0.099
AV: 00:00:00 / 00:02:23 (0%) A-V:  0.107
AV: 00:00:00 / 00:02:23 (0%) A-V:  0.122 Dropped: 0/1
AV: 00:00:00 / 00:02:23 (0%) A-V:  0.101 Dropped: 0/2
AV: 00:00:00 / 00:02:23 (0%) A-V:  0.101 Dropped: 0/3
AV: 00:00:00 / 00:02:23 (0%) A-V:  0.085 Dropped: 0/3
AV: 00:00:00 / 00:02:23 (0%) A-V:  0.060 Dropped: 0/3
AV: 00:00:00 / 00:02:23 (0%) A-V:  0.080 Dropped: 0/3
AV: 00:00:00 / 00:02:23 (0%) A-V:  0.092 Dropped: 0/3
AV: 00:00:00 / 00:02:23 (0%) A-V:  0.119 Dropped: 0/3
AV: 00:00:00 / 00:02:23 (0%) A-V:  0.119 Dropped: 0/4
[ ... ]
AV: 00:00:29 / 00:02:23 (20%) A-V:  0.137 Dropped: 0/424
AV: 00:00:29 / 00:02:23 (20%) A-V:  0.000 Dropped: 0/424
[ao/null] buffer underrun
AV: 00:00:29 / 00:02:23 (20%) A-V:  0.000 Dropped: 0/424
Exiting... (End of file)

I would like to add two metrics where the values are 0 and 424 (coming from a split of 0/424).
The interesting value is the last one because it is the last update giving the frames drop but how can I update the metric as it was previously added with 0/1 when appeared first ?
What would be the regexp in this case?

The current regexp is:

regex_map = { "dropped_frame_rendering": (re.compile(r'(\d+) Dropped'), "frames"),
              "dropped_frame_decoding": (re.compile(r'(\d+) Dropped'), "frames") }

And the function updating the metric is:

def update_output(self, context):
        super(Mplayer, self).update_output(context)
        # Update the output within the specified execution context with the
        # metrics and artifacts form this workload iteration.
        outfile = os.path.join(context.output_directory, 'mplayer.output')
        with open(outfile, 'w') as wfh:
            wfh.write(self.output)

        with open(outfile) as fh:
            for line in fh:
                for label, (regex, units) in regex_map.items():
                    match = regex.search(line)
                    if match:
                        context.add_metric(label, float(match.group(3)), units)

**Comment by marcbonnici** [comment]
Apologies if I've misunderstood the question however my understanding is that you essentially want to be able to extract only the `0` and `424` from the final `AV: 00:00:29 / 00:02:23 (20%) A-V: 0.000 Dropped: 0/424` line ignoring all the previous line that match the format? 

If so I think the easiest way would be to have a regex that matches the full line, something like:
`Dropped: (?P<dropped>\d+)\/(?P<total>\d+)` 
And instead of adding the match directly as a metric just save them in variables causing the old values to be overwritten upon each new match and once you have finished looping over the file  you add then add them as a metric leaving you with only that last line values. 

Is this the sort of thing you were looking for?

**Comment by dlezcano** [comment]
Yes, that's correct. Indeed I can do that with an intermediate variable. 
Would it make sense to add an update_metric method to the context object?

Regarding the regexp, what does the name 'dropped' ? Is it a way to name the group?

**Comment by dlezcano** [comment]
Finally double checked my self :)
Everything working fine, thanks for your help
