### ISSUE TITLE
how to run an agenda/workload without ssh/adb

### ISSUE THREAD

**Issue by khilman** [ARM-software/workload-automation#1022]
Is it possible to run an agenda/workload without an ssh/adb connection?  

IOW, the workload would be copied to to the target, but the usb/network interfaces would be disabled during the workload execution, and then re-established after workload completion.

The goal here is to measure the power consumption of a workload, but the power consumption of the usb or network connection will affect the power consumption of the workload.

**Comment by setrofim** [comment]
No, this is not possible out of the box -- WA design assumes a direct connection to the target. We typically look at deltas rather than absolute values, so the effect of the connection is assumed to cancel out. We also tend to favour measuring SoC  rather than device power where possible (though with consumer devices, that's rarely the case).

Note that in the case of adb, there no persistent session, unlike SSH, so if you have a means of disabling the connection while the workload is running, WA won't notice, unless you have enabled instrumentation that relies on it (I think logcat polling might be enabled by default these day, but it can be disabled with device configuration). 

If you have a means of disabling the connection from the host, you can write a simple instrument to do it. If it needs to be done from the device, then you're probably better off integrating it into the workload --- create a shell script that disables the connection, invokes the workload, waits for the workload to finish, enables the connection, and then `target.kick_off()` it from the workload. You'd then need some way of figuring out when the workload is finished host-side; doing something like [`adb_list_devices`](https://github.com/ARM-software/devlib/blob/master/devlib/utils/android.py#L541) in a loop to see when it reappears might work.

The sames, in principle, can be applied to SSH-based connections, as WA will automatically try to re-connect if it detects a dropped connection.

**Comment by khilman** [comment]
Thanks @setrofim for the detailed response.  Very helpful.

Related Q: since WA assumes a direct connect, is a serial console / UART one of the possibilities?  Rather than using adb/ssh (which might consume usb/net power) using just a UART might be another  way of minimizing overall device consumption.

**Comment by setrofim** [comment]
In theory, yes, in practice we do not have a connection implemented for it. We use UART in a limited way on VersatileExpress-based devices (e.g. Juno) to query the IP address as part of establishing the initial connection, but driving the main interaction over UART in a generic way would be problematic due to its various idiosyncrasies, so it's not something we've looked at implemented.

**Comment by khilman** [comment]
OK, thanks again for all the help.

I see there's something called `serialmon` for doing basic logging over the serial, but not the main connection: https://workload-automation.readthedocs.io/en/latest/plugins/instruments.html#serialmon
