### ISSUE TITLE
How to run a android apllication

### ISSUE THREAD

**Issue by zhizhouzh** [ARM-software/workload-automation#21]
Hi experts,

I tried to run the below commands:

    wa run -f angrybirds

firstly, it compains 'CRITICAL <<Workload angrybirds>'s apk> could not be found'. Then I cp angrybirds.apk to /usr/local/lib/python2.7/dist-packages/wlauto/workloads/angrybirds. But it still compains:

CRITICAL <<Workload angrybirds>'s revent> could not be found

So I use the revent to generate a revent.bin, and copy the file to  /usr/local/lib/python2.7/dist-packages/wlauto/workloads/angrybirds. But it doesn't help.

Is that because of  I assigned the wrong file name for the revent file? If so, what's the right one?

Thank you!

**Comment by setrofim** [comment]
Hi zhizhouzh,

Yes, revent files need to be named `<device name>.(setup|run).revent`; please see revent section documentation for details:
http://pythonhosted.org/wlauto/revent.html#using-revent-with-workloads

(Also, you can put these files under `~/.workload_automation/dependencies/angrybirds` rather than copying them into `/usr/local`.)

**Comment by zhizhouzh** [comment]
After several other problems were solved, howerver, at last, I successed to run angry birds now. 
Thank you very much!
