### ISSUE TITLE
Port Sqlite Output Processor 

### ISSUE THREAD

**Issue by marcbonnici** [ARM-software/workload-automation#630]

**Comment by setrofim** [comment]
From having a quick look into this earlier, it should be relatively straight-forward, _except_ that the WA2 implementation accesses `context.run_info`, which is currently not being passed to WA3 output processor methods, however that would make the result processor methods more unwieldy for a relatively niche (?) case. It's worth pausing to consider the possible approaches here, and what would be the most appropriate.

Off the top of my head the alternatives are:

1. Adding `run_info` to the method arguments, as described above.
2. Adding it on initialization (either on creation, or as an argument to `initialize()`). This would make sense because a processor is associated with a "run" more or less by definition. (While the same could also be said for `target_info` at the moment, it might not always be the case -- consider the potential future multi-target scenarios).
3. Passing the entire `context`, a la WA2,  rather than individual info objects. This is pretty much a no-go, as it will make it more or less impossible to guarantee processors can be run offline, which is a hard requirement. 
4. Rather than going wider (`context`) go narrower -- pass only a single "identifier" for a run. This will make it easier to implement offline processing (even without full WA output structure), but is not very future proof (e.g. we'll want to access other parts of `run_info` when we com to implement the full-featured SQL uploader -- date, duration, etc).
5. Make `sqlitedb` and instrument rather than an output processor, giving it access to the full `context` without placing this burden on other processors. This makes little sense, both conceptually (no need for a target connection, or  real time host state), and practically  (we _want_ to be able to run `sqlitedb` offline, e.g. when uploading existing results to a new database). Mentioning here for completeness.
6. ???

**Comment by mwasilew** [comment]
@setrofim do you have any estimated ETA for supporting sqlite in WAv3 ?

**Comment by setrofim** [comment]
This is slated for our `rel 3.0/2.7` milestone, so it will be in the 3.0 release. It's currently expected to be beginning of April. We'll  prioritise porting this so that it will appear in the `next` branch sooner rather than later, but can't commit to a particular deadline beyond the milestone.

**Comment by mwasilew** [comment]
Thanks! That is good enough for me :)

**Comment by setrofim** [comment]
I was able to carve out some time this afternoon, so this is now in: https://github.com/ARM-software/workload-automation/commit/e6f7d3fcdec04754fe01f58186cc88024e2658df
