### ISSUE TITLE
Disable all instruments

### ISSUE THREAD

**Issue by dlezcano** [ARM-software/workload-automation#636]
Hi WA3,

in the documentation it is specified we can disable a specific instrumentation with the syntax ~<instrument>. In the configuration I want to disable all instrumentation without knowledge of what have been put in the global configuration file (eg. ~cpufreq) in order to begin the test in a clean place but without impacting my personal configuration. Is it possible to have some kind of '~*'.

For example: instrumentation: [ 'file_poller', ~* ]

**Comment by setrofim** [comment]
There is nothing like that at the moment. We'll look into adding this in the future. In the mean time, as a workaround, you can bypass the global configuration file by setting `WA_USER_DIRECTORY` to point to a different location from the default `~/.workload_autiomation`:

`WA_USER_DIRECTORY=../dummy-user-directory  wa run [...]`

Note, that if the directory does not already exist, it will be created, long with the default config file (which would have some instruments enabled by default);  so you should point it to an existing directory with a `config.yaml` that does not have any instruments enabled.

**Comment by marcbonnici** [comment]
That would be great, thanks for taking a look at it.

**Comment by Rahlubenru** [comment]
A couple of questions regarding how it is envisaged this will work.

First, does this want to disable only instruments, both instruments and processors, or have separate syntax for instruments and/or processors?

Second how would specifying it in a config file interact with the other augments entries in the same file? The easy options would be to either disable them all or to not have any effect on them all. Harder, because the toggle set does not remember insertion order so we can't currently know the relative position, would be to disable only those preceding it in the config.

**Comment by marcbonnici** [comment]
I think as we are trying to abstract the difference between instruments and processors for users, and the fact that this will most likely be used as part of a test run, it would make sense to use this to just disable both instruments and processors together with the one special character, allowing the user to explicitly re-enable anything they require. And we've been thinking that this shouldn't use the ``~*`` notation, as this could imply that the inverse operation of using a ``*`` would enabled everything, which probably wouldn't make much sense, so would suggest using something like ``~~`` instead to indicate this. 

As for the ordering, I think that we could say that the level of config that contains this glyph, that would then become the base state in terms of re-enabling augmentations. Meaning that only augmentations specified at that level and higher would be enabled, e.g. if ``~~`` was specified in the agenda config section then only any other augmentations also present in that file would be used during the run, whereas if this was supplied in an additional config file via the ``-c`` flag then this would allow you to ignore the default augmentations in ``WA_USER_DIRECTORY`` however still allow for any augmentations explicitly specified in the agenda to still be used (as well as others also in that config file). And lastly this would be able to be supplied with the ``--disable`` command which would globally disable everything.

To deal with this config merging we're thinking that implementing this in the ``merge`` function of the ``toggleset`` type would make the most sense. So when performing the merge of the augmentation lists, if we're merging a set that contains the disable glyph, essentially, the other set would be dropped and the set containing the glyph (with the glyph removed) would then be returned as the result.

**Comment by Rahlubenru** [comment]
I have a version that I think performs as specified above unless I misinterpreted something at #733

I didn't put it in the `merge` function because if it is not done before `JobSpec.configuration[name].set_value` then they are re-enabled by `generate_job_specs`

I'm also not completely sure about my implementation for the use with `--disable` but I figure I'm at a good point to submit for feedback.

**Comment by setrofim** [comment]
Implemented by https://github.com/ARM-software/workload-automation/pull/734
