### ISSUE TITLE
Failed to run templerun2 with revent errors

### ISSUE THREAD

**Issue by Leo-Yan** [ARM-software/workload-automation#968]
Hi there,

When I run the templerun2 workload with the latest workload-automation code base, it reports the failure with '\<\<Workload templerun2\>'s revent\> could not be found'; but the revent files have been placed in the dependencies folder:

~~~
$ ls ~/.workload_automation/dependencies/templerun2/revent_files/ -l
total 40
-rw-rw-r-- 1 leoy leoy 36864 Apr 23 13:55 generic_android.run.revent
-rw-rw-r-- 1 leoy leoy    88 Apr 23 13:55 generic_android.startup.revent
~~~

Since the device name is defined as 'generic_android', so I followed the naming convention as generic_android.{run|startup}.revent.

Also enclosed the workload agenda and the run.log for your reference:
[run.log.txt](https://github.com/ARM-software/workload-automation/files/3106613/run.log.txt)
[templerun2.yaml.txt](https://github.com/ARM-software/workload-automation/files/3106614/templerun2.yaml.txt)

Thanks a lot for helping.

**Comment by marcbonnici** [comment]
Hello,

The device name that WA uses is model of the device itself rather than the target name 'generic_android' as this allows for WA to differentiate between multiple targets that may be used. 

In order to get the device name for you device you can run `adb shell getprop ro.product.model` and this will return the name that you would then use for naming the revent files. 

Alternatively you can also use our [record command](https://workload-automation.readthedocs.io/en/stable/user_information.html#record) which can automate the recording process for you.
E.g `wa record -w templerun2 -s -r` would launch templerun2 and them prompt you to perform recordings for the setup and run stages, naming and placing the files to their correct locations. 

Please let me know if this works for you.

**Comment by Leo-Yan** [comment]
Hi @marcbonnici,

Yes, I tested these two methods, both can resolve my issue.  Thanks a lot for the guidance.

Just want to remind, seems to me the WA documentation is easy to introduce confusion for this part, I read the document [1] section "Convention for Naming revent Files for Revent Workloads" and searched the github issue [2], both gave me the impression to use the device name which defined in WA config file.  Should update related doc for this?

Very appreciate for the helping!

[1] https://media.readthedocs.org/pdf/workload-automation/latest/workload-automation.pdf 
[2] https://github.com/ARM-software/workload-automation/issues/968

**Comment by marcbonnici** [comment]
No problem, that's good to hear.

And yes thank you for the feedback, I will try and clarify this in the documentation to prevent further confusion.
